import yaml
import boto3
import time 

stream = open("server.yaml",'r')

data = yaml.load(stream)

### create instance
s = boto3.Session(region_name="us-west-2")
ec2 = s.resource('ec2')

instance = ec2.create_instances(ImageId='ami-0528a5175983e7f28',KeyName='infra-master-key',InstanceType=data["server"]["instance_type"],SubnetId='subnet-04879e65a37dc5864',MaxCount=1,MinCount=1) 
print("instance created")
