import yaml
import boto3

with open("server.yaml", 'r') as stream:
    try:
        #  print(yaml.safe_load(stream))
        x = yaml.safe_load(stream)
        print(x['server']['instance_type'])
        client = boto3.client('ec2')
        resp = client.run_instances('ami-7d0c6314',
                      InstanceType= x["server"]["instance_type"],
                      MinCount= x["server"]["min_count"],
                      MaxCount= x["server"]["max_count"])
    except yaml.YAMLError as exc:
        print(exc)

 
#for instance in resp['Instances']:
#    print(instance['instanceId'])
