server:
  instance_type: t2.micro
  region: "us-west-2"
  ami_type: 'amzn2'
  architecture: 'x86_64'
  root_device_type: ebs
  keyName: 'fetchreward'
  subnet: 'subnet-04879e65a37dc5864'
  virtualization_type: hvm
  min_count: 1
  max_count: 1
  volumes:
    - device: /dev/xvda
      size_gb: 10
      type: gp2
      mount: /
    - device: /dev/xvdf
      size_gb: 20
      type: gp2
      mount: /data
  users:
    - login: user1
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDE1/ruN48o6d1/CEshPWx7nqSQmKO+ovwyj3WT/Z+1nMk8CoFaSmyyJm9ZuwcEaPN7uqBg+H6er1nORXF1VpOrA7n5ULsZsG2xyEto/E2C0A/66KrGEA6URKfJpOsQq2iEH/ESha2tokVB7hpwJcRROQnLs87YkrHOUNwoIdozo67cRt6jpEjVj4QWVUj0+nBsPoN5vl/ev5qRFbVQT4a8vFBsuFPshBAqzbTVzQ2AH835wAhTUiT8tDe1XeGBGDD1SNREh5A8l0MR3EAhLbTvn15n2Y9Pqjjk98MMgpLW4UTF0ZrUo6QY475mF7+9ZiXOKMwRhjEa8oIssARepKejpFgzswU1mcdj+PibldNMzT9O6qh1QTD0nUYM5/WoazWcveTydAlRhkhV8LVM/U1gj+3BMCC2LUENtvywedqRbutWTA6TEUdESYMCDXx/m1p6KBGG6p8+xCzmRjcLKc2QZPY0TMkQeY52HkJvZ2j/yK38CqFrzoXnZ23uKP+63p11e33z9XJp1ruxbFiUSmFPsVVYpBtsxqhEvG80FBzdfpQoRD7r+leWKZ/LC376FIv3T+djbWqCvKFTvEEU6kxsFe8zgLefCkAv/y1FX1OWtWA7Hjj6bN7wW+rLIP5ubuyqFA8B04IE4NeYNHaT6EHXNHdlHo4qr6J8avnrj0vPFQ== mitchell.chang11@gmail.com
    - login: user2
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDE1/ruN48o6d1/CEshPWx7nqSQmKO+ovwyj3WT/Z+1nMk8CoFaSmyyJm9ZuwcEaPN7uqBg+H6er1nORXF1VpOrA7n5ULsZsG2xyEto/E2C0A/66KrGEA6URKfJpOsQq2iEH/ESha2tokVB7hpwJcRROQnLs87YkrHOUNwoIdozo67cRt6jpEjVj4QWVUj0+nBsPoN5vl/ev5qRFbVQT4a8vFBsuFPshBAqzbTVzQ2AH835wAhTUiT8tDe1XeGBGDD1SNREh5A8l0MR3EAhLbTvn15n2Y9Pqjjk98MMgpLW4UTF0ZrUo6QY475mF7+9ZiXOKMwRhjEa8oIssARepKejpFgzswU1mcdj+PibldNMzT9O6qh1QTD0nUYM5/WoazWcveTydAlRhkhV8LVM/U1gj+3BMCC2LUENtvywedqRbutWTA6TEUdESYMCDXx/m1p6KBGG6p8+xCzmRjcLKc2QZPY0TMkQeY52HkJvZ2j/yK38CqFrzoXnZ23uKP+63p11e33z9XJp1ruxbFiUSmFPsVVYpBtsxqhEvG80FBzdfpQoRD7r+leWKZ/LC376FIv3T+djbWqCvKFTvEEU6kxsFe8zgLefCkAv/y1FX1OWtWA7Hjj6bN7wW+rLIP5ubuyqFA8B04IE4NeYNHaT6EHXNHdlHo4qr6J8avnrj0vPFQ== mitchell.chang11@gmail.com
